version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - db
